model_list:
  - model_name: ollama/llama3.1  # This is just an alias
    litellm_params:
      model: ollama/llama3.1            # Match exactly what `ollama list` shows
      api_base: http://localhost:11434
      api_key: sk-no-key-needed
      api_type: ollama
      llm_provider: ollama
      function_calling: true
      json_output: true
      structured_output: true

litellm_settings:
  drop_params: true
  set_verbose: true