model_list:
  - model_name: ollama/llama3.1
    litellm_params:
      provider: ollama
      api_type: ollama
      model: ollama/llama3.1
      api_base: http://localhost:11434
      api_key: sk-no-key-needed
      function_calling: true
      json_output: true
      structured_output: true
      timeout: 600000
      max_batch_size: 1
      max_concurrent_requests: 1
  - model_name: ollama/deepseek-coder:6.7b
    litellm_params:
      provider: ollama
      api_type: ollama
      model: ollama/deepseek-coder:6.7b
      api_base: http://localhost:11434
      api_key: sk-no-key-needed
      function_calling: true
      json_output: true
      structured_output: true
      timeout: 600000
      max_batch_size: 1
      max_concurrent_requests: 1

  - model_name: ollama/nomic-embed-text
    litellm_params:
      provider: ollama
      api_type: ollama
      model: ollama/nomic-embed-text
      api_base: http://localhost:11434
      api_key: sk-no-key-needed
      timeout: 600000

litellm_settings:
  drop_params: true
